#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TypeANumber.Resource", IsApplication=true)]

namespace TypeANumber
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BaseGameUtils.Resource.Attribute.buttonSize = global::TypeANumber.Resource.Attribute.buttonSize;
			global::BaseGameUtils.Resource.Attribute.circleCrop = global::TypeANumber.Resource.Attribute.circleCrop;
			global::BaseGameUtils.Resource.Attribute.colorScheme = global::TypeANumber.Resource.Attribute.colorScheme;
			global::BaseGameUtils.Resource.Attribute.imageAspectRatio = global::TypeANumber.Resource.Attribute.imageAspectRatio;
			global::BaseGameUtils.Resource.Attribute.imageAspectRatioAdjust = global::TypeANumber.Resource.Attribute.imageAspectRatioAdjust;
			global::BaseGameUtils.Resource.Attribute.scopeUris = global::TypeANumber.Resource.Attribute.scopeUris;
			global::BaseGameUtils.Resource.Color.common_action_bar_splitter = global::TypeANumber.Resource.Color.common_action_bar_splitter;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_dark = global::TypeANumber.Resource.Color.common_google_signin_btn_text_dark;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_dark_default = global::TypeANumber.Resource.Color.common_google_signin_btn_text_dark_default;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_dark_disabled = global::TypeANumber.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_dark_focused = global::TypeANumber.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_dark_pressed = global::TypeANumber.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_light = global::TypeANumber.Resource.Color.common_google_signin_btn_text_light;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_light_default = global::TypeANumber.Resource.Color.common_google_signin_btn_text_light_default;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_light_disabled = global::TypeANumber.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_light_focused = global::TypeANumber.Resource.Color.common_google_signin_btn_text_light_focused;
			global::BaseGameUtils.Resource.Color.common_google_signin_btn_text_light_pressed = global::TypeANumber.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_dark = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_dark;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_dark_default = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_dark_default;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_dark_disabled = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_dark_disabled;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_dark_focused = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_dark_focused;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_dark_pressed = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_dark_pressed;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_light = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_light;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_light_default = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_light_default;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_light_disabled = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_light_disabled;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_light_focused = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_light_focused;
			global::BaseGameUtils.Resource.Color.common_plus_signin_btn_text_light_pressed = global::TypeANumber.Resource.Color.common_plus_signin_btn_text_light_pressed;
			global::BaseGameUtils.Resource.Drawable.common_full_open_on_phone = global::TypeANumber.Resource.Drawable.common_full_open_on_phone;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_dark = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_dark_disabled = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_dark_disabled;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_dark_pressed = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_dark_pressed;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_light = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_light;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_light_disabled = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_light_disabled;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_icon_light_pressed = global::TypeANumber.Resource.Drawable.common_google_signin_btn_icon_light_pressed;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_dark = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_dark;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_dark_disabled = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_dark_disabled;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_dark_pressed = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_dark_pressed;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_light = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_light;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_light_disabled = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_light_disabled;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_light_focused = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_light_normal = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::BaseGameUtils.Resource.Drawable.common_google_signin_btn_text_light_pressed = global::TypeANumber.Resource.Drawable.common_google_signin_btn_text_light_pressed;
			global::BaseGameUtils.Resource.Drawable.common_ic_googleplayservices = global::TypeANumber.Resource.Drawable.common_ic_googleplayservices;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_dark = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_dark;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_dark_focused = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_dark_focused;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_dark_normal = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_dark_normal;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_light = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_light;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_light_disabled = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_light_disabled;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_light_focused = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_light_focused;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_light_normal = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_light_normal;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_icon_light_pressed = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_icon_light_pressed;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_dark = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_dark;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_dark_disabled = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_dark_disabled;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_dark_focused = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_dark_focused;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_dark_normal = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_dark_normal;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_dark_pressed = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_dark_pressed;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_light = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_light;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_light_disabled = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_light_disabled;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_light_focused = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_light_focused;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_light_normal = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_light_normal;
			global::BaseGameUtils.Resource.Drawable.common_plus_signin_btn_text_light_pressed = global::TypeANumber.Resource.Drawable.common_plus_signin_btn_text_light_pressed;
			global::BaseGameUtils.Resource.Drawable.ic_plusone_medium_off_client = global::TypeANumber.Resource.Drawable.ic_plusone_medium_off_client;
			global::BaseGameUtils.Resource.Drawable.ic_plusone_small_off_client = global::TypeANumber.Resource.Drawable.ic_plusone_small_off_client;
			global::BaseGameUtils.Resource.Drawable.ic_plusone_standard_off_client = global::TypeANumber.Resource.Drawable.ic_plusone_standard_off_client;
			global::BaseGameUtils.Resource.Drawable.ic_plusone_tall_off_client = global::TypeANumber.Resource.Drawable.ic_plusone_tall_off_client;
			global::BaseGameUtils.Resource.Id.adjust_height = global::TypeANumber.Resource.Id.adjust_height;
			global::BaseGameUtils.Resource.Id.adjust_width = global::TypeANumber.Resource.Id.adjust_width;
			global::BaseGameUtils.Resource.Id.auto = global::TypeANumber.Resource.Id.auto;
			global::BaseGameUtils.Resource.Id.dark = global::TypeANumber.Resource.Id.dark;
			global::BaseGameUtils.Resource.Id.icon_only = global::TypeANumber.Resource.Id.icon_only;
			global::BaseGameUtils.Resource.Id.light = global::TypeANumber.Resource.Id.light;
			global::BaseGameUtils.Resource.Id.none = global::TypeANumber.Resource.Id.none;
			global::BaseGameUtils.Resource.Id.standard = global::TypeANumber.Resource.Id.standard;
			global::BaseGameUtils.Resource.Id.wide = global::TypeANumber.Resource.Id.wide;
			global::BaseGameUtils.Resource.Integer.google_play_services_version = global::TypeANumber.Resource.Integer.google_play_services_version;
			global::BaseGameUtils.Resource.String.ApplicationName = global::TypeANumber.Resource.String.ApplicationName;
			global::BaseGameUtils.Resource.String.Hello = global::TypeANumber.Resource.String.Hello;
			global::BaseGameUtils.Resource.String.auth_google_play_services_client_facebook_display_name = global::TypeANumber.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::BaseGameUtils.Resource.String.auth_google_play_services_client_google_display_name = global::TypeANumber.Resource.String.auth_google_play_services_client_google_display_name;
			global::BaseGameUtils.Resource.String.common_google_play_services_api_unavailable_text = global::TypeANumber.Resource.String.common_google_play_services_api_unavailable_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_enable_button = global::TypeANumber.Resource.String.common_google_play_services_enable_button;
			global::BaseGameUtils.Resource.String.common_google_play_services_enable_text = global::TypeANumber.Resource.String.common_google_play_services_enable_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_enable_title = global::TypeANumber.Resource.String.common_google_play_services_enable_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_install_button = global::TypeANumber.Resource.String.common_google_play_services_install_button;
			global::BaseGameUtils.Resource.String.common_google_play_services_install_text_phone = global::TypeANumber.Resource.String.common_google_play_services_install_text_phone;
			global::BaseGameUtils.Resource.String.common_google_play_services_install_text_tablet = global::TypeANumber.Resource.String.common_google_play_services_install_text_tablet;
			global::BaseGameUtils.Resource.String.common_google_play_services_install_title = global::TypeANumber.Resource.String.common_google_play_services_install_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_invalid_account_text = global::TypeANumber.Resource.String.common_google_play_services_invalid_account_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_invalid_account_title = global::TypeANumber.Resource.String.common_google_play_services_invalid_account_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_network_error_text = global::TypeANumber.Resource.String.common_google_play_services_network_error_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_network_error_title = global::TypeANumber.Resource.String.common_google_play_services_network_error_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_notification_ticker = global::TypeANumber.Resource.String.common_google_play_services_notification_ticker;
			global::BaseGameUtils.Resource.String.common_google_play_services_restricted_profile_text = global::TypeANumber.Resource.String.common_google_play_services_restricted_profile_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_restricted_profile_title = global::TypeANumber.Resource.String.common_google_play_services_restricted_profile_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_sign_in_failed_text = global::TypeANumber.Resource.String.common_google_play_services_sign_in_failed_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_sign_in_failed_title = global::TypeANumber.Resource.String.common_google_play_services_sign_in_failed_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_unknown_issue = global::TypeANumber.Resource.String.common_google_play_services_unknown_issue;
			global::BaseGameUtils.Resource.String.common_google_play_services_unsupported_text = global::TypeANumber.Resource.String.common_google_play_services_unsupported_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_unsupported_title = global::TypeANumber.Resource.String.common_google_play_services_unsupported_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_update_button = global::TypeANumber.Resource.String.common_google_play_services_update_button;
			global::BaseGameUtils.Resource.String.common_google_play_services_update_text = global::TypeANumber.Resource.String.common_google_play_services_update_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_update_title = global::TypeANumber.Resource.String.common_google_play_services_update_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_updating_text = global::TypeANumber.Resource.String.common_google_play_services_updating_text;
			global::BaseGameUtils.Resource.String.common_google_play_services_updating_title = global::TypeANumber.Resource.String.common_google_play_services_updating_title;
			global::BaseGameUtils.Resource.String.common_google_play_services_wear_update_text = global::TypeANumber.Resource.String.common_google_play_services_wear_update_text;
			global::BaseGameUtils.Resource.String.common_open_on_phone = global::TypeANumber.Resource.String.common_open_on_phone;
			global::BaseGameUtils.Resource.String.common_signin_button_text = global::TypeANumber.Resource.String.common_signin_button_text;
			global::BaseGameUtils.Resource.String.common_signin_button_text_long = global::TypeANumber.Resource.String.common_signin_button_text_long;
			global::BaseGameUtils.Resource.String.gamehelper_app_misconfigured = global::TypeANumber.Resource.String.gamehelper_app_misconfigured;
			global::BaseGameUtils.Resource.String.gamehelper_license_failed = global::TypeANumber.Resource.String.gamehelper_license_failed;
			global::BaseGameUtils.Resource.String.gamehelper_sign_in_failed = global::TypeANumber.Resource.String.gamehelper_sign_in_failed;
			global::BaseGameUtils.Resource.String.gamehelper_unknown_error = global::TypeANumber.Resource.String.gamehelper_unknown_error;
			global::BaseGameUtils.Resource.Styleable.LoadingImageView = global::TypeANumber.Resource.Styleable.LoadingImageView;
			global::BaseGameUtils.Resource.Styleable.LoadingImageView_circleCrop = global::TypeANumber.Resource.Styleable.LoadingImageView_circleCrop;
			global::BaseGameUtils.Resource.Styleable.LoadingImageView_imageAspectRatio = global::TypeANumber.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::BaseGameUtils.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::TypeANumber.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::BaseGameUtils.Resource.Styleable.SignInButton = global::TypeANumber.Resource.Styleable.SignInButton;
			global::BaseGameUtils.Resource.Styleable.SignInButton_buttonSize = global::TypeANumber.Resource.Styleable.SignInButton_buttonSize;
			global::BaseGameUtils.Resource.Styleable.SignInButton_colorScheme = global::TypeANumber.Resource.Styleable.SignInButton_colorScheme;
			global::BaseGameUtils.Resource.Styleable.SignInButton_scopeUris = global::TypeANumber.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_action_bar_splitter = 2130968584;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_text_dark = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_dark_default = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_signin_btn_text_dark_disabled = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_signin_btn_text_dark_focused = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_text_dark_pressed = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int common_google_signin_btn_text_light = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_signin_btn_text_light_default = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_light_disabled = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_light_focused = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_signin_btn_text_light_pressed = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_plus_signin_btn_text_dark = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int common_plus_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_plus_signin_btn_text_dark_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_plus_signin_btn_text_dark_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_plus_signin_btn_text_dark_pressed = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int common_plus_signin_btn_text_light = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int common_plus_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_plus_signin_btn_text_light_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_plus_signin_btn_text_light_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_plus_signin_btn_text_light_pressed = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_search = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_launcher = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_plusone_medium_off_client = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_plusone_small_off_client = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_plusone_standard_off_client = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_plusone_tall_off_client = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int adjust_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int adjust_width = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int auto = 2131230723;
			
			// aapt resource value: 0x7f080021
			public const int btn_unlock = 2131230753;
			
			// aapt resource value: 0x7f080004
			public const int dark = 2131230724;
			
			// aapt resource value: 0x7f080015
			public const int digit_button_0 = 2131230741;
			
			// aapt resource value: 0x7f080012
			public const int digit_button_1 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int digit_button_2 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int digit_button_3 = 2131230740;
			
			// aapt resource value: 0x7f08000f
			public const int digit_button_4 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int digit_button_5 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int digit_button_6 = 2131230737;
			
			// aapt resource value: 0x7f08000c
			public const int digit_button_7 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int digit_button_8 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int digit_button_9 = 2131230734;
			
			// aapt resource value: 0x7f080016
			public const int digit_button_clear = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int easy_mode_button = 2131230746;
			
			// aapt resource value: 0x7f080009
			public const int fragment_container = 2131230729;
			
			// aapt resource value: 0x7f08001b
			public const int hard_mode_button = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int hello = 2131230745;
			
			// aapt resource value: 0x7f080000
			public const int icon_only = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int light = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int none = 2131230728;
			
			// aapt resource value: 0x7f080017
			public const int ok_score_button = 2131230743;
			
			// aapt resource value: 0x7f080024
			public const int score_display = 2131230756;
			
			// aapt resource value: 0x7f08000b
			public const int score_input = 2131230731;
			
			// aapt resource value: 0x7f080025
			public const int scoreblurb = 2131230757;
			
			// aapt resource value: 0x7f08000a
			public const int screen_gameplay = 2131230730;
			
			// aapt resource value: 0x7f080018
			public const int screen_menu = 2131230744;
			
			// aapt resource value: 0x7f080023
			public const int screen_win = 2131230755;
			
			// aapt resource value: 0x7f08001c
			public const int show_achievements_button = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int show_leaderboards_button = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int sign_in_bar = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int sign_in_button = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int sign_out_bar = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int sign_out_button = 2131230754;
			
			// aapt resource value: 0x7f080001
			public const int standard = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int wide = 2131230722;
			
			// aapt resource value: 0x7f080026
			public const int win_ok_button = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int win_screen_sign_in_bar = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int win_screen_sign_in_button = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int win_screen_signed_in_bar = 2131230761;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_gameplay = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_mainmenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_win = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050024
			public const int ApplicationName = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int Hello = 2131034147;
			
			// aapt resource value: 0x7f05003b
			public const int achievement = 2131034171;
			
			// aapt resource value: 0x7f05002a
			public const int achievement_arrogant = 2131034154;
			
			// aapt resource value: 0x7f050038
			public const int achievement_arrogant_toast_text = 2131034168;
			
			// aapt resource value: 0x7f050028
			public const int achievement_bored = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int achievement_humble = 2131034153;
			
			// aapt resource value: 0x7f050039
			public const int achievement_humble_toast_text = 2131034169;
			
			// aapt resource value: 0x7f05002b
			public const int achievement_leet = 2131034155;
			
			// aapt resource value: 0x7f05003a
			public const int achievement_leet_toast_text = 2131034170;
			
			// aapt resource value: 0x7f050026
			public const int achievement_prime = 2131034150;
			
			// aapt resource value: 0x7f050037
			public const int achievement_prime_toast_text = 2131034167;
			
			// aapt resource value: 0x7f050027
			public const int achievement_really_bored = 2131034151;
			
			// aapt resource value: 0x7f050033
			public const int achievements_not_available = 2131034163;
			
			// aapt resource value: 0x7f050025
			public const int app_id = 2131034149;
			
			// aapt resource value: 0x7f050030
			public const int app_name = 2131034160;
			
			// aapt resource value: 0x7f05001d
			public const int auth_google_play_services_client_facebook_display_name = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int auth_google_play_services_client_google_display_name = 2131034140;
			
			// aapt resource value: 0x7f05004b
			public const int choose_difficulty = 2131034187;
			
			// aapt resource value: 0x7f050049
			public const int clear = 2131034185;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_api_unavailable_text = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_enable_button = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_text = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_title = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_phone = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_text_tablet = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_title = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_invalid_account_text = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_invalid_account_title = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_network_error_text = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_network_error_title = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_notification_ticker = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_restricted_profile_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_restricted_profile_title = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_sign_in_failed_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_sign_in_failed_title = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_unknown_issue = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_unsupported_text = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_unsupported_title = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_update_button = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_title = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_wear_update_text = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int common_open_on_phone = 2131034132;
			
			// aapt resource value: 0x7f05001a
			public const int common_signin_button_text = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int common_signin_button_text_long = 2131034139;
			
			// aapt resource value: 0x7f05003f
			public const int digit0 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int digit1 = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int digit2 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int digit3 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int digit4 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int digit5 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int digit6 = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int digit7 = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int digit8 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int digit9 = 2131034184;
			
			// aapt resource value: 0x7f05004c
			public const int easy = 2131034188;
			
			// aapt resource value: 0x7f050035
			public const int easy_mode_explanation = 2131034165;
			
			// aapt resource value: 0x7f050020
			public const int gamehelper_app_misconfigured = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int gamehelper_license_failed = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int gamehelper_sign_in_failed = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int gamehelper_unknown_error = 2131034146;
			
			// aapt resource value: 0x7f05004d
			public const int hard = 2131034189;
			
			// aapt resource value: 0x7f050036
			public const int hard_mode_explanation = 2131034166;
			
			// aapt resource value: 0x7f05003e
			public const int initial_input = 2131034174;
			
			// aapt resource value: 0x7f05002c
			public const int leaderboard_easy = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int leaderboard_hard = 2131034157;
			
			// aapt resource value: 0x7f050034
			public const int leaderboards_not_available = 2131034164;
			
			// aapt resource value: 0x7f05004a
			public const int ok = 2131034186;
			
			// aapt resource value: 0x7f05004e
			public const int see_your_progress = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int show_achievements = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int show_leaderboards = 2131034192;
			
			// aapt resource value: 0x7f050055
			public const int sign_in_to_upload_this_score = 2131034197;
			
			// aapt resource value: 0x7f050051
			public const int sign_in_why = 2131034193;
			
			// aapt resource value: 0x7f050053
			public const int sign_out = 2131034195;
			
			// aapt resource value: 0x7f050032
			public const int signed_out_greeting = 2131034162;
			
			// aapt resource value: 0x7f05002e
			public const int signing_in = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int signing_out = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int title_activity_main = 2131034161;
			
			// aapt resource value: 0x7f05003d
			public const int what_score_do_you_deserve = 2131034173;
			
			// aapt resource value: 0x7f050052
			public const int you_are_signed_in = 2131034194;
			
			// aapt resource value: 0x7f050054
			public const int you_win = 2131034196;
			
			// aapt resource value: 0x7f05003c
			public const int your_progress_will_be_uploaded = 2131034172;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
